### ISSUE TITLE
Text off-center on Game Screen

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/area-model-algebra#10]
**Test device**
MacBook Air M1 chip

**Operating System**
14.1.2

**Browser**
Safari 17.1.2

**Problem description**
For https://github.com/phetsims/qa/issues/1031, in locales other than English the "Choose Your Level!" statement is off-center. This is most easily seen with ?stringTest=dynamic.

**Steps to reproduce**
1. Add ?stringTest=dynamic to end of url
2. Go to the Game screen
3. Press right arrow

**Visuals**
<img width="781" alt="Screenshot 2024-01-25 at 11 15 36 AM" src="https://github.com/phetsims/area-model-algebra/assets/87318828/f11dcfd7-095c-4283-8af3-ac17b0ea07f3">

<img width="610" alt="Screenshot 2024-01-25 at 11 50 37 AM" src="https://github.com/phetsims/area-model-algebra/assets/87318828/59b22fb3-8ecf-4242-bc57-aaacf7696f99">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Area Model Algebra_面積模型與代數‬
URL: https://phet-dev.colorado.edu/html/area-model-algebra/1.3.0-dev.1/phet/area-model-algebra_all_phet.html?regionAndCulture=latinAmerica
Version: 1.3.0-dev.1 2024-01-20 02:30:37 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15
Language: en-US
Window: 1351x710
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Luisav1** [comment]
This is fixed in the commit above. This is how it looks like with `stringTest=dynamicLocale`.
![image](https://github.com/phetsims/area-model-algebra/assets/52978048/cc47bfca-4eb5-41fd-81ee-19197f578011)

**Comment by Luisav1** [comment]
This is now fixed more robustly by linking to the `boundsProperty` of the `chooseYourLevelText` and positioning the text in there. This is what it looks like now with `stringTest=dynamic`.
![image](https://github.com/phetsims/area-model-algebra/assets/52978048/44f5e85c-fe11-48a3-a0de-fbecc319fcc4)

Closing.
