### ISSUE TITLE
Decrease stroke around Level 1 block

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/area-model-algebra#11]
**Test device**
MacBook Air M1 chip

**Operating System**
14.1.2

**Browser**
Safari 17.1.2

**Problem description**
For https://github.com/phetsims/qa/issues/1031, the outline around the block in Level 1 is thicker than the other blocks. 
@amanda-phet said this is something she would normally fix. 

<img width="592" alt="Screenshot 2024-01-26 at 2 18 42 PM" src="https://github.com/phetsims/area-model-algebra/assets/87318828/254115ab-f9ec-4b03-987c-7b934e0aa9db">

**Comment by Nancy-Salpepi** [comment]
Seen in the USA, Africa and Africa(modest) character sets (same image used in all three).

**Comment by amanda-phet** [comment]
New image uploaded. Over to @Luisav1

**Comment by Luisav1** [comment]
The artwork is integrated and it's looking good! Leaving this open for QA.

**Comment by Luisav1** [comment]
Closing since there's no more work here.
