### ISSUE TITLE
Pan to numberpad?

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/area-model-algebra#12]
**Test device**
iPad
**Operating System**
iPadOS 17.3
**Browser**
Safari
**Problem description**
For https://github.com/phetsims/qa/issues/1031
When zoomed in with pan and zoom, should the screen pan to the number pad when it is opened? It does not currently, but I would expect it to pan to have it in screen if it isn't when it is opened.

**Comment by KatieWoe** [comment]
This applies to https://github.com/phetsims/qa/issues/1032 as well.

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe! I just saw this one go by. Panning like this will only happen automatically if alt input is enabled and the sim is using KeypadDialog. It looks like neither are the case here. @Luisav1 if panning to the Keypad is important for the release of this sim I would be happy to help add that.

**Comment by marlitas** [comment]
Quick message exchange with @jessegreenberg seems like we can implement this in a straightfoward way with something like `animatedPanZoomSingleton.listener.panToNode( keypad )`.

@Luisav1 and I will pair on converting TermKeypadPanel to a KeypadDialog.

**Comment by Luisav1** [comment]
Thanks @jessegreenberg and @marlitas! The screen animates to center on the keypad, if it is visible, in the commit above. This is ready for review.

**Comment by amanda-phet** [comment]
This looks nice! I click on the edit icon and the sim pans over to the number pad. I like it!

**Comment by marlitas** [comment]
Those commits look good to me. I think this is ready to close! @Luisav1 feel free to reopen if there's remaining work I'm forgetting about.
