### ISSUE TITLE
Game Level Numbers Are Off

### ISSUE THREAD

**Issue by JRomero0613** [phetsims/area-model-algebra#4]
In the latest round of dev testing seen here: https://github.com/phetsims/QA/issues/157 I have seen that on the game screen when playing a game and finishing the game the score will come up with the wrong level, one less than what it should be. For example completing game level 1 reads out Level completed: 0 and the score.

**Comment by lmulhall-phet** [comment]
Related to phetsims/vegas/issues/73.

**Comment by lmulhall-phet** [comment]
I'm guessing https://github.com/phetsims/area-model-common/commit/4191ca21e3c6962257dd75b68639d93a4d1f14d2 hasn't been applied to Area Model?

**Comment by jonathanolson** [comment]
Should be fixed in master with the above commit, can you verify?

**Comment by JRomero0613** [comment]
I have just checked master and the issue has been fixed, closing
