### ISSUE TITLE
Add Africa, Africa Modest, Asia, Latin America, and Oceania character sets

### ISSUE THREAD

**Issue by marlitas** [phetsims/area-model-algebra#7]
First steps is to create the preferences model and character sets structure in this sim.

**Comment by amanda-phet** [comment]
Icons are uploaded! Over to @Luisav1

**Comment by Luisav1** [comment]
The artwork is integrated now! @amanda-phet could you review to make sure it's looking good?

**Comment by amanda-phet** [comment]
The icons looked good, but now we're replacing them with the svg images. Let me know when those are ready for review.

**Comment by marlitas** [comment]
Looks like that work is ready for you to review @amanda-phet. Sending your way.

**Comment by amanda-phet** [comment]
SVG screen icons are uploaded.

**Comment by Luisav1** [comment]
The svg files are all integrated now and ready for your review @amanda-phet.

**Comment by amanda-phet** [comment]
All of the artwork looks good to me!
