### ISSUE TITLE
Turn on UI sounds

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/area-model-algebra#8]
This sim should have game sounds on, but the other UI sounds should be off.

**Comment by Luisav1** [comment]
Talking with @amanda-phet, we'll instead try out using tambo's grab/release sounds for the handle of the area model, which solves the issue of only some interactive elements having sound.

**Comment by amanda-phet** [comment]
The grab/release sounds are in, and I checked over all of the things that make sounds and everything sounds pretty good. However the grab sound in particular seems too loud. In comparison with My Solar System, both grab and release are much louder in this sim, but their checkboxes and buttons seem the same. Can we adjust grab/release volume?

**Comment by Luisav1** [comment]
The grab/release sounds are from `solar-system-common`, so they're specific to My Solar System and Kepler's Laws. Talking with @amanda-phet, we're going to keep the current sounds in AMA and AMM since the sounds were getting too custom.

Leaving this open for QA to test.

**Comment by Nancy-Salpepi** [comment]
UI sounds are on in 1.3.0-dev.1
Closing!
